name: Analytics Service Build and Push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # Enable manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Step 4: Run unit tests
      - name: Run unit tests
        run: mvn clean test

      # Step 5: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Step 6: Set up Docker Buildx (optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 7: Build the Docker image with a dynamic tag
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/lugx-analytics:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/lugx-analytics:${{ github.run_id }}

      # Step 8: Push the Docker image to Docker Hub
      - name: Push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/lugx-analytics:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/lugx-analytics:${{ github.run_id }}